### ISSUE TITLE
32 bit constant issues

### ISSUE THREAD

**Issue by zherczeg** [Samsung/walrus#163]
It seems sometimes 32 bit constant pairs are packed into 64 bit constants. This is a big problem for jit, since it cannot track constants properly. Is there a way to detect such const64 byte codes? I suspect that is not possible, that a constant is used as both 64 bit and a pair of 32 bit, so at parsing time we could replace them with two 32 bit constants in the latter case. A flag or a byte code type would be enough.

**Comment by ksh8281** [comment]
Can you give a example code?

**Comment by ksh8281** [comment]
It is not bug. this is intended operation for copy arguments without reference function arguments type
(f64.const 64)  (f32.const 32)
(copy4B, copy4B) (copy4B)
each copy count of type is computed by `function valueFunctionCopyCount`
but It could be confusing. may I add a function for original position?

**Comment by zherczeg** [comment]
I suspect this is something new. Are these true:
- affect calls / callIndirects only
- all data type are split into pointer sized fragments, so a 128 bit value is 4 moves on 32 bit, and 2 moves on 64 bit?
- 32 bit moves are 64 bit moves on 64 bit?

If this is true, I can create an algorithm to detect which "arguments" needs to be ignored by jit.

**Comment by ksh8281** [comment]
Yes, three things are true.

**Comment by zherczeg** [comment]
It looks like End opcode is also affected.
