### ISSUE TITLE
[JIT] assertion failed in X64 JIT

### ISSUE THREAD

**Issue by clover2123** [Samsung/walrus#202]
* Environment:  Ubuntu 20.04 with intel x64 CPU
* Run a sample tensorflow app same as the previous issue https://github.com/Samsung/walrus/issues/184#issuecomment-1791954741 
* Description of error
```sh
Assertion failed at ../third_party/sljit/sljit_src/sljitLir.c:2641
```

For x64 environment, lwnode with walrus-jit presents an error (assertion error) above.

**Comment by clover2123** [comment]
Build walrus with the latest version of the main branch

**Comment by zherczeg** [comment]
May I get some mire info for reproducing this bug? It does not shown here.

I am currently using these hashes:
Walrus: 1d852c62188094b38ec060ed7b1d51ede07867fe (latest)
Sljit: e09319736d051a248dffdf81257162ea331a2b4f (not the latest, but walrus uses it atm)

I confirmed with gdb that jit is compiled and used in lwnode. The project is compiled in debug mode.

The assertion line info is strange as well:
https://github.com/zherczeg/sljit/blob/e09319736d051a248dffdf81257162ea331a2b4f/sljit_src/sljitLir.c#L2641

The `sljit_has_cpu_feature(SLJIT_HAS_SIMD)` should not fail unless you run it on a 15 year old machine (unlikely). Compiling the inline assembly with `cpuid` sometimes incorrect with some compilers, that can also be an issue.

**Comment by zherczeg** [comment]
I was able to reproduce! The code needs to be compiled in release mode. And it is cpuid. The `"memory"` keyword is missing from the assembly block, and it was added in a later version of the jit compiler:

https://github.com/zherczeg/sljit/commit/62c91605a8b20f74ab99902b338f626cc7551904

Perhaps we need a compiler update patch.

**Comment by clover2123** [comment]
Many thanks for the quick update!
